"""add validity score and rating to videos

Revision ID: d8f087e9f6e0
Revises: dc0a2f02a681
Create Date: 2026-09-19 15:09:20.633791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8f087e9f6e0"
down_revision: str | Sequence[str] | None = "dc0a2f02a681"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("validity_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("validity_rating", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_column("validity_rating")
        batch_op.drop_column("validity_score")

    # ### end Alembic commands ###
