"""add fact check columns to videos

Revision ID: dc0a2f02a681
Revises: ae46e80923a1
Create Date: 2026-09-19 11:05:10.130181

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc0a2f02a681"
down_revision: str | Sequence[str] | None = "ae46e80923a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_educational", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("thesis", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("hallucinated", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_column("hallucinated")
        batch_op.drop_column("thesis")
        batch_op.drop_column("is_educational")

    # ### end Alembic commands ###
