import { useState } from "react";
import styled from "styled-components";

import { count, days, hours, number, percent } from "./format.js";
import { bodyText, focusRing, smallText } from "./primitives.jsx";

const MAX_PHRASES = 3;

function Service({ href, children }) {
  return (
    <ServiceLink href={href} target="_blank" rel="noopener noreferrer">
      {children}
    </ServiceLink>
  );
}

// The backend sends fields; the wording lives here, so a value is phrased one way and
// the summary can never drift from the rows beneath it. Rows carry only what the
// summary doesn't already say.
const CRITERIA = {
  gptzero_transcript: {
    name: "Transcript analysis",
    summary: ({ predicted_class: verdict, confidence_score: confidence }) =>
      `Reads as ${WRITING[verdict] ?? "unclear"} writing${confident(confidence)}.`,
    about: (
      <>
        <Service href="https://gptzero.me">GPTZero</Service> reads the transcript and rates how much
        of it was written by a language model, sentence by sentence. It judges the words, not the
        voice reading them.
      </>
    ),
    rows: (evidence) => [
      ["AI probability", percent(evidence.ai_probability)],
      ["Flagged sentences", percent(evidence.flagged_sentence_ratio)],
    ],
  },
  elevenlabs_voice: {
    name: "Text-to-speech likelihood",
    summary: ({ probability }, deduction) =>
      deduction > 0
        ? `An ElevenLabs voice reads this, ${percent(probability)} match.`
        : `No ElevenLabs voice here, ${percent(probability)} match. Other AI voices aren't covered.`,
    about: (
      <>
        <Service href="https://elevenlabs.io">ElevenLabs</Service> listens to the first minute and
        reports whether the narration was generated by ElevenLabs.
      </>
    ),
  },
  filler_words: {
    name: "Filler words",
    summary: (evidence, deduction) =>
      deduction > 0
        ? "Noticeably few filler words found."
        : "Narrates at a natural rate with occassional filler words.",
    rows: (evidence) => [
      ["Fillers words found", count(evidence.filler_count, "words")],
      ["Rate", number(evidence.rate_per_100_words, "fillers / 100 words")],
    ],
  },
  upload_pattern: {
    name: "Upload history",
    summary: (evidence) => `A new video roughly every ${hours(evidence.median_gap_hours)}.`,
    rows: (evidence) => [["Videos sampled", number(evidence.uploads_sampled)]],
  },
  account_age: {
    name: "Channel creation date",
    summary: (evidence) =>
      `The channel's oldest video was uploaded ${days(evidence.oldest_upload_age_days)} ago.`,
  },
  channel_history: {
    name: "Similar videos",
    summary: (evidence) =>
      `${count(evidence.videos_sampled, "other video")} from this channel average ${number(evidence.average_score)} out of 100.`,
  },
};

const WRITING = { human: "human", ai: "AI", mixed: "part human, part AI" };

// Why a criterion had nothing to say. Kept apart from the criteria themselves because
// several share the same reason.
const REASONS = {
  transcript_too_short: (e) =>
    `The transcript is too short to judge \u2014 ${count(e.word_count, "word")}, and this needs ${e.words_needed}.`,
  needs_auto_captions: () =>
    "Only YouTube's auto-captions keep the stumbles this looks for, but these captions were written.",
  too_few_uploads: () => "The channel has too few videos to show a pattern.",
  no_uploads: () => "The channel has no public videos to date it by.",
  no_siblings: () => "No other videos from this channel have been analyzed yet.",
  no_audio: () => "There was no audio to listen to.",
  no_credentials: () => "Skipped: no usable Anthropic credentials.",
  not_educational: () => "Nothing here states checkable facts, so there was nothing to check.",
  upstream_error: () => "This check couldn't run.",
};

// The fact check isn't scored, so the breakdown leaves it out.
const HIDDEN = new Set(["fact_check"]);

function confident(confidence) {
  if (!Number.isFinite(confidence) || confidence >= 0.9) return "";
  return confidence >= 0.6 ? ", though not certainly" : ", but it is unsure";
}

/** The one line under a criterion: its finding, or why it had none. */
function summarise(item, config) {
  const evidence = item.evidence ?? {};
  if (item.reason) return REASONS[item.reason]?.(evidence) ?? null;
  if (item.applied && config.summary) return config.summary(evidence, item.deduction);
  // Evaluations stored before the backend sent fields still carry their own sentence.
  return item.detail ?? null;
}

const List = styled.ol`
  margin: 0;
  padding: 0;
  list-style: none;
`;

const Toggle = styled.button`
  display: flex;
  align-items: center;
  gap: var(--ait-space-3);
  width: calc(100% + 2 * var(--ait-space-2));
  min-height: var(--ait-control-height);
  margin: 0 calc(-1 * var(--ait-space-2));
  padding: var(--ait-space-2);
  border: none;
  border-radius: var(--ait-radius-chip);
  background: transparent;
  color: inherit;
  font-family: inherit;
  font-size: 1.4rem;
  line-height: 2rem;
  font-weight: 500;
  text-align: left;
  cursor: pointer;
  transition: background var(--ait-duration-fast) var(--ait-ease-exit);

  &:hover {
    background: var(--ait-tonal);
  }

  &:active {
    background: var(--ait-tonal-hover);
  }

  &:focus-visible {
    ${focusRing}
  }
`;

const Index = styled.span`
  display: flex;
  flex: 0 0 auto;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border: 1px solid var(--ait-text);
  border-radius: 50%;
  ${smallText}
`;

const Points = styled.span`
  margin-left: auto;
  color: var(--ait-${(props) => props.$tone});
  font-weight: ${(props) => (props.$tone === "text-secondary" ? 400 : 500)};
  font-variant-numeric: tabular-nums;
`;

const Details = styled.div`
  display: flex;
  flex-direction: column;
  gap: var(--ait-space-2);
  margin: var(--ait-space-1) 0 var(--ait-space-2) 11px;
  padding-left: calc(var(--ait-space-4) + var(--ait-space-2));
  border-left: 2px solid var(--ait-text);
`;

const Detail = styled.p`
  margin: 0;
  ${bodyText}
  color: var(--ait-text-secondary);
`;

const Label = styled.dt`
  margin: 0;
  ${bodyText}
  color: var(--ait-text-secondary);
`;

const About = styled.p`
  /* Flush with the rule above it, so its first letter lines up with the line. */
  margin: 0 0 var(--ait-space-2) 11px;
  color: var(--ait-text-secondary);
  ${smallText}
`;

const ServiceLink = styled.a`
  color: var(--ait-cta);
  text-decoration: underline;

  &:hover {
    text-decoration-thickness: 2px;
  }

  &:focus-visible {
    outline: 2px solid var(--ait-text);
    outline-offset: 2px;
    border-radius: 2px;
  }
`;

const Value = styled.dd`
  margin: 0;
  ${bodyText}
  overflow-wrap: anywhere;
`;

const Rows = styled.dl`
  display: flex;
  flex-direction: column;
  gap: var(--ait-space-1);
  margin: 0;
`;

const Pair = styled.div`
  display: flex;
  gap: var(--ait-space-1);
`;

const PhraseList = styled.ul`
  display: flex;
  flex-direction: column;
  gap: var(--ait-space-2);
  margin: var(--ait-space-1) 0 0;
  padding: 0;
  list-style: none;
`;

const Phrase = styled.li`
  display: flex;
  align-items: baseline;
  gap: var(--ait-space-2);
  font-size: 1.4rem;
  line-height: 2.2rem;
`;

const Time = styled.button`
  flex: 0 0 auto;
  padding: 0;
  border: none;
  background: none;
  color: var(--ait-cta);
  font: inherit;
  font-weight: 500;
  font-variant-numeric: tabular-nums;
  cursor: pointer;

  &:hover {
    text-decoration: underline;
  }

  &:focus-visible {
    outline: 2px solid var(--ait-text);
    outline-offset: 2px;
    border-radius: 2px;
  }
`;

const Quote = styled.span`
  display: -webkit-box;
  overflow: hidden;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 8;
  line-clamp: 8;
`;

const Marked = styled.mark`
  padding: 2px var(--ait-space-1);
  border-radius: var(--ait-space-1);
  background: var(--ait-marker);
  color: inherit;
  box-decoration-break: clone;
  -webkit-box-decoration-break: clone;
`;

const PhraseLabel = styled.p`
  margin: 0;
  ${bodyText}
  font-weight: 500;
`;

export function Breakdown({ evaluation }) {
  const [open, setOpen] = useState(null);
  const items = (evaluation.breakdown ?? []).filter((item) => !HIDDEN.has(item.criterion));

  return (
    <List>
      {items.map((item, index) => {
        const config = CRITERIA[item.criterion] ?? {};
        const evidence = item.evidence ?? {};
        const [text, tone] = points(item);
        const summary = summarise(item, config);
        const expanded = open === index;
        return (
          <li key={item.criterion}>
            <Toggle
              type="button"
              aria-expanded={expanded}
              onClick={() => setOpen(expanded ? null : index)}
            >
              <Index>{index + 1}</Index>
              <span>{config.name ?? humanize(item.criterion)}</span>
              <Points $tone={tone}>{text}</Points>
            </Toggle>
            {expanded && (
              <>
                <Details>
                  {summary && <Detail>{summary}</Detail>}
                  <Phrases sentences={evidence.flagged_sentences} />
                  <RowList entries={config.rows?.(evidence) ?? []} />
                </Details>
                {config.about && <About>{config.about}</About>}
              </>
            )}
          </li>
        );
      })}
    </List>
  );
}

function Phrases({ sentences }) {
  const phrases = (Array.isArray(sentences) ? sentences : [])
    .filter((entry) => entry?.text)
    .slice(0, MAX_PHRASES);
  if (!phrases.length) return null;

  const seek = (start) => {
    const video = document.querySelector("video");
    if (video) video.currentTime = start;
  };

  return (
    <div>
      <PhraseLabel>Likely AI phrases:</PhraseLabel>
      <PhraseList>
        {phrases.map(({ text, start_seconds: start }) => (
          <Phrase key={text}>
            {Number.isFinite(start) && (
              <Time
                type="button"
                aria-label={`Jump to ${timestamp(start)}`}
                onClick={() => seek(start)}
              >
                {timestamp(start)}
              </Time>
            )}
            <Quote>
              <Marked>{text}</Marked>
            </Quote>
          </Phrase>
        ))}
      </PhraseList>
    </div>
  );
}

function RowList({ entries }) {
  const rows = entries.filter(([, value]) => value != null && value !== "");
  if (!rows.length) return null;
  return (
    <Rows>
      {rows.map(([label, value]) => (
        <Pair key={label}>
          <Label>{label}:</Label>
          <Value>{value}</Value>
        </Pair>
      ))}
    </Rows>
  );
}

function points({ applied, deduction }) {
  if (!applied) return ["n/a", "text-secondary"];
  if (deduction > 0) return [`−${number(deduction)}`, "slop"];
  if (deduction < 0) return [`+${number(-deduction)}`, "human"];
  return ["0", "text-secondary"];
}

function timestamp(seconds) {
  const minutes = Math.floor(seconds / 60);
  return `${String(minutes).padStart(2, "0")}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`;
}

function humanize(name) {
  const text = String(name).replace(/_/g, " ");
  return text.charAt(0).toUpperCase() + text.slice(1);
}
